### ISSUE TITLE
Groove Music 的图标有 "官方" 的 iconfont 可用

### ISSUE THREAD

**Issue by nondanee** [MXXXXXS/aqua-player#1]
找一下 Groove Music for Android 的 APK，解压就有了 :)
[SegMVR2.zip](https://github.com/MXXXXXS/aqua-player/files/3586442/SegMVR2.zip)

**Comment by MXXXXXS** [comment]
> 找一下 Groove Music for Android 的 APK，解压就有了 :)
> [SegMVR2.zip](https://github.com/MXXXXXS/aqua-player/files/3586442/SegMVR2.zip)

多谢!

**Comment by nondanee** [comment]
客气
